### ISSUE TITLE
Create OSCORE section

### ISSUE THREAD

**Issue by chrysn** [anr-bmbf-pivot/draft-dns-over-coap#1]
It *probably* doesn't need to say much more than that it largely does the same as DTLS with the respective security considerations applied -- and that applications can just use whatever they already ship code for.

Potential aspects to point out for the reader's convenience:
* It's relatively cheap to have a dedicated security context for DNS separate from other applications, making it easy to separate privileges on the server side. In such cases, the URI path that lends itself to the application is `/` as that makes the most compact requests.
* ... anything else?

**Comment by miri64** [comment]
> * ... anything else?

Can we validate server identity with OSCORE? If not, DTLS+OSCORE still has a use case that should be mentioned (given of course DTLS is used in a mode where the server identity can be validated ;-)).

**Comment by chrysn** [comment]
> Can we validate server identity with OSCORE?

Yes; that's determined at setup time. (For example, when established
through EDHOC, the client has authenticated the server from a
certificate or a known RPK).

(Server identity is even validated in group mode).

**Comment by miri64** [comment]
Done in latest version.
