### ISSUE TITLE
CoRE technology dependencies

### ISSUE THREAD

**Issue by chrysn** [anr-bmbf-pivot/draft-dns-over-coap#10]
I find some text around CoRE dependencies needlessly constraining -- not without precedent in CoRE documents, but maybe we can do better.

Example:

> If the FETCH or POST method are used and block-wise transfer [RFC7959] is supported by the client, more than one CoAP request message MAY be used. If more than one CoAP request message is used to encode the DNS query, it must be chained together using the Block1 option in those CoAP requests.

I see no good reason why CoD can't be used with any successor to the original Block options -- but this text rules it out. (Yeah it's not a normative MUST but still strong-worded).

I think it'd be better for general composability of the components if we phrased this more openly; the strictness can still be in an MTI set of base things, maybe like this:

> The block-wise transfer mechsnism of CoAP [RFC7959] enables the transfer of large DNS requests in FETCH and POST; DoC servers SHOULD support it. Clients MAY use any mechanism to send large requests \, but (if they send large requests in the first place) SHOULD fall back to using Block1 if the server does not support them.

(We can discuss whether these are to be SHOULDs or MUSTs, but that's not this discussion.)

**Comment by miri64** [comment]
This is "fixed" in the current version: All direct references to block-wise transfer were removed. Only the distinction "body" and "payload" remain.
